apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30777
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 30700
  selector:
    app: jenkins
