apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: observability
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "32b7c21891-bucket-1"
    ibm.io/secret-name: "cos-write-access"
    ibm.io/endpoint: "https://s3.private.mil01.cloud-object-storage.appdomain.cloud"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-s3fs-standard-perf-regional
